# Generated by Django 2.2.4 on 2019-08-28 09:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='organism',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.assay')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.instrument')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.organism')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.project')),
            ],
        ),
        migrations.CreateModel(
            name='sample_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('lat', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('lon', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='virus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
                ('taxon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sample_virus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.sample')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.virus')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.site'),
        ),
        migrations.AddField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.sample_type'),
        ),
    ]
